// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdge6sWwuZSSod6tz368KEanVRNcSEXdQ',
    appId: '1:994984326426:web:865b46397afd9221ee28a3',
    messagingSenderId: '994984326426',
    projectId: 'demeter-solution',
    authDomain: 'demeter-solution.firebaseapp.com',
    storageBucket: 'demeter-solution.firebasestorage.app',
    measurementId: 'G-7XGDPDYETX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAttJDu4cNdNtbHE-p1Wx1HNAfijlP00ps',
    appId: '1:994984326426:android:b0b8babf31fc8b26ee28a3',
    messagingSenderId: '994984326426',
    projectId: 'demeter-solution',
    storageBucket: 'demeter-solution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQyNVCLzjhae8vaxyisdRClGi-ai4LK9w',
    appId: '1:994984326426:ios:e308b648dfc0bb30ee28a3',
    messagingSenderId: '994984326426',
    projectId: 'demeter-solution',
    storageBucket: 'demeter-solution.firebasestorage.app',
    iosBundleId: 'com.example.demetersolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQyNVCLzjhae8vaxyisdRClGi-ai4LK9w',
    appId: '1:994984326426:ios:e308b648dfc0bb30ee28a3',
    messagingSenderId: '994984326426',
    projectId: 'demeter-solution',
    storageBucket: 'demeter-solution.firebasestorage.app',
    iosBundleId: 'com.example.demetersolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdge6sWwuZSSod6tz368KEanVRNcSEXdQ',
    appId: '1:994984326426:web:431074e1a7f0db5bee28a3',
    messagingSenderId: '994984326426',
    projectId: 'demeter-solution',
    authDomain: 'demeter-solution.firebaseapp.com',
    storageBucket: 'demeter-solution.firebasestorage.app',
    measurementId: 'G-NP3R1S4QL3',
  );
}
